export declare function abs(a: number): void;
export declare function alphabetize(s: string): void;
export declare function and(a: boolean, b: boolean): void;
export declare function average(a: number[]): void;
export declare function ceiling(a: number): void;
export declare function clamp(a: number, b: number, c: number): void;
export declare function combinations(array: number[], n: number): void;
export declare function contain(array: string[], word: string): void;
export declare function countSpaces(str: string): void;
export declare function cube(a: number): void;
export declare function decrement(a: number): void;
export declare function difference(a: number, b: number): void;
export declare function endsWith(targetString: string, substring: string): void;
export declare function exponent(a: number, b: number): void;
export declare function factorial(a: number): void;
export declare function fibonacci(a: number): void;
export declare function firstUniqueChar(s: string): void;
export declare function floor(a: number): void;
export declare function gcd(a: number, b: number): void;
export declare function increment(a: number): void;
export declare function indexOf(arr: string[], element: string): void;
export declare function isEven(a: number): void;
export declare function isNegativeZero(a: number): void;
export declare function isOdd(a: number): void;
export declare function isPositiveZero(a: number): void;
export declare function last<T>(a: T): void;
export declare function lerp(a: number, b: number, c: number): void;
export declare function lowercase(s: string): void;
export declare function max(a: number, b: number): void;
export declare function mean(a: number, b: number): void;
export declare function median(list: number[]): void;
export declare function min(a: number, b: number): void;
export declare function mode(list: number[]): void;
export declare function nor(a: number, b: number): void;
export declare function permute(array: number[]): void;
export declare function power(a: number, b: number): void;
export declare function prime(a: number): void;
export declare function product(a: number, b: number): void;
export declare function pythagorean(a: number, b: number): void;
export declare function quotient(a: number, b: number): void;
export declare function remainder(a: number, b: number): void;
export declare function removeLast(a: string[]): void;
export declare function reverse<T>(value: T): void;
export declare function rot13(value: string): void;
export declare function round(a: number): void;
export declare function secondLargest(a: number[]): void;
export declare function sign(a: number): void;
export declare function square(a: number): void;
export declare function squareRoot(a: number): void;
export declare function startsWith(targetString: string, substring: string): void;
export declare function sum(a: number, b: number): void;
export declare function swapCase(str: string): void;
export declare function uppercase(s: string): void;
export declare function without<T>(array: number[], itemsToRemove: T): void;
export declare function xor(a: number, b: number): void;
