module.exports = {
  abs: require('./abs'),
  alphabetize: require('./alphabetize'),
  combinations: require('./combinations'),
  contain: require('./contain'),
  difference: require('./difference'),
  exponent: require('./exponent'),
  factorial: require('./factorial'),
  fibonacci: require('./fibonacci'),
  gcd:require('./gcd'),
  increment: require('./increment'),
  last: require('./last'),
  max: require('./max'),
  median: require('./median'),
  min: require('./min'),
  permute: require('./permute'),
  power: require('./power'),
  prime: require('./prime'),
  product: require('./product'),
  pythagorean: require('./pythagorean'),
  quotient: require('./quotient'),
  remainder: require('./remainder'),
  reverse: require('./reverse'),
  square: require('./square'),
  squareRoot: require('./squareRoot'),
  sum: require('./sum'),
  without: require('./without'),
  xor: require('./xor'),
};
