module.exports = {
  abs: require('./abs'),
  alphabetize: require('./alphabetize'),
  difference: require('./difference'),
  product: require('./product'),
  quotient: require('./quotient'),
  exponent: require('./exponent'),
  remainder: require('./remainder'),
  square: require('./square'),
  sum: require('./sum'),
  power: require('./power'),
  xor: require('./xor'),
  reverse: require('./reverse'),
  squareRoot: require('./squareRoot'),
  increment: require('./increment'),
  pythagorean: require('./pythagorean'),
  fibonacci: require('./fibonacci'),
  max: require('./max'),
  factorial: require('./factorial'),
  min: require('./min'),
  contain: require('./contain'),
  last: require('./last'),
  pythagorean: require('./pythagorean'),
  median: require('./median'),
  prime: require('./prime')
};
