module.exports = {
  abs: require('./abs'),
  alphabetize: require('./alphabetize'),
  contain: require('./contain'),
  difference: require('./difference'),
  exponent: require('./exponent'),
  factorial: require('./factorial'),
  fibonacci: require('./fibonacci'),
  increment: require('./increment'),
  last: require('./last'),
  max: require('./max'),
  median: require('./median'),
  min: require('./min'),
  power: require('./power'),
  product: require('./product'),
  pythagorean: require('./pythagorean'),
  quotient: require('./quotient'),
  remainder: require('./remainder'),
  reverse: require('./reverse'),
  square: require('./square'),
  squareRoot: require('./squareRoot'),
  sum: require('./sum'),
  xor: require('./xor'),
};
